Repository tripleadev/zsk-amnesty, pull requests merged in 2021-12, with the labels that each got.

#25 Admin Panel
  CODEOWNERS
  LICENSE
  README.md
  amnesty-logo.png
  components/letters/LettersForm.tsx
  components/letters/LettersTable.tsx
  lib/auth/withApiAuth.ts
  lib/fetcher.ts
  lib/withApiMethods.ts
  lib/withApiValidation.ts
  package.json
  pages/_app.tsx
  pages/admin/admins.tsx
  pages/admin/dashboard.tsx
  pages/admin/destinations.tsx
  pages/admin/letters.tsx
  pages/api/admins.ts
  pages/api/classes.ts
  pages/api/destinations.ts
  pages/api/letters/batch.ts
  pages/api/letters/index.ts
  pages/api/login.ts
  prisma/migrations/20211127111705_/migration.sql
  prisma/migrations/20211127111836_/migration.sql
  prisma/migrations/20211127123033_/migration.sql
  prisma/migrations/20211130190838_/migration.sql
  prisma/migrations/20211130194144_/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  yarn.lock
Labels: feature

#20 refactor: export the snackbar with an allert to the toast component
  components/common/Toast.tsx
  components/letters/LettersForm.tsx
  pages/admin/admins.tsx
  pages/admin/destinations.tsx
Labels: in progress

#29 Feat/admin account management
  pages/admin/admins.tsx
  pages/admin/changePassword.tsx
  pages/admin/dashboard.tsx
  pages/admin/destinations.tsx
  pages/api/admins.ts
  pages/api/changePassword.ts
Labels: feature

#30 Stats page + Admins management
  components/admin/LoginForm.tsx
  components/common/Toast.tsx
  components/letters/LettersForm.tsx
  components/stats/Authors.tsx
  components/stats/Classes.tsx
  components/stats/Destinations.tsx
  components/stats/Total.tsx
  lib/stats/anonymousLettersTo.ts
  lib/stats/format.ts
  lib/stats/lettersOfClass.ts
  lib/stats/lettersToDestination.ts
  lib/stats/stats.ts
  lib/stats/topAuthors.ts
  lib/stats/totalAuthors.ts
  lib/stats/totalDestinations.ts
  lib/stats/totalLetters.ts
  package.json
  pages/admin/admins.tsx
  pages/admin/changePassword.tsx
  pages/admin/dashboard.tsx
  pages/admin/destinations.tsx
  pages/api/admins.ts
  pages/api/changePassword.ts
  pages/api/letters/batch.ts
  pages/api/stats.ts
  pages/index.tsx
  prisma/migrations/20211127180642_/migration.sql
  prisma/schema.prisma
  public/AmnestyTradeGothic.ttf
  public/AmnestyTradeGothicBold.ttf
  public/logo.png
  styles/globals.css
  yarn.lock
Labels: feature

#35 Letters deleting
  components/letters/LettersTable.tsx
  package.json
  pages/_document.tsx
  pages/admin/admins.tsx
  pages/api/letters/index.ts
  pages/index.tsx
  prisma/schema.prisma
Labels: feature

#40 Fix Excel stats export
  lib/exportStats/addValuesToWorksheet.ts
  lib/exportStats/excelFileSetup.ts
  lib/stats/topAuthors.ts
  pages/api/exportStats.ts
Labels: bug
